### PR TITLE
Cascading dependency digests

### PR DESCRIPTION
**Pull request by tenorviol**
Do-over from https://github.com/mutewinter/digest-brunch/pull/22

This is a major refactor, sorry about the big diff.
I have another pull request up that if merged will reduce the size of this diff here: https://github.com/mutewinter/digest-brunch/pull/23
The intent of this PR is to fix this issue: https://github.com/mutewinter/digest-brunch/issues/7 

For my project, cascading digests are important because we digest both the css and the binary assets (referenced within css). I was running into bugs where some css files wouldn't get digests replaced because they had been renamed prior to their own digest replace step.

The fix requires introducing a [topological sort](http://en.wikipedia.org/wiki/Topological_sorting) after dependency discovery. The rewrites are then done in order of least dependent to most dependent. I've added a couple of tests for these cases. We might need more tests here...

I was also able to fix the false positive test scenario by replacing the fake-fs with the real file system.

### CODE REVIEW

**Comment by tenorviol** [comment]
@Tomtomgo The infix stuff has been re-added and the tests for it work now. Please confirm this satisfies your use case.

**Comment by Tomtomgo** [comment]
@tenorviol I checked it and it does the infixing for alternative file versions correctly again, thanks so much!

**Comment by mutewinter** [comment]
This is amazing. I can't even. Thanks so much @tenorviol!

Is this ready to merge since it's working for @Tomtomgo?

**Comment by tenorviol** [comment]
It's working for us. So that's two use cases. ;) The reason I wanted to fix the tests was to have some confidence in it being ready. All tests pass, so I say go for it.

**Comment by mutewinter** [comment]
Merged and released!

**Comment by tenorviol** [comment]
Nice. Thanks!

It should be pretty easy to fix this now: https://github.com/mutewinter/digest-brunch/issues/3 because the file containing the relative link is now available in the correct scope. I kind of had this in mind, but it wasn't a priority at the time. I may do that if I get bored over next while.

**Pull request merged**
