### PR TITLE
Cascading dependency digests

### PR DESCRIPTION
**Pull request by tenorviol**
This is a major refactor, sorry about the big diff. The intent is to fix this issue: https://github.com/mutewinter/digest-brunch/issues/7 

For my project it was important because we digest both the css and the binary assets (referenced within css). I was running into bugs where some css files wouldn't get digests replaced because they had been renamed prior to their own digest replace step.

The fix requires introducing a [topological sort](http://en.wikipedia.org/wiki/Topological_sorting) after dependency discovery. The rewrites are then done in order of least dependent to most dependent. I've added a couple of tests for these cases. We might need more tests here...

I was also able to fix the false positive test scenario by replacing the fake-fs with the real file system.

### CODE REVIEW

**Comment by Tomtomgo** [comment]
Very nice! I checked the code out and it seems to work well.

What doesn't work anymore however is the `infixes` option. The infix version doesn't get a digest (so otter.jpeg gets a digest, otter@2x doesn't get that same digest. It seems to be removed [here](https://github.com/eero-inc/digest-brunch/commit/de9e4a426286a2a747ffd7ef9dac469336cdbd80#diff-2fbc5085a7bbe6fb696a1a3b75a6f420L156).

**Comment by tenorviol** [comment]
Oh yeah. I didn't understand the feature. Let me look at that.

**Comment by Tomtomgo** [comment]
The use is for serving images for different resolution, like retina screens. There's a [retina.js](http://imulus.github.io/retinajs/) which helps you with this. The idea of it is that there are multiple versions of an image that all get the same digest but have a different infix (e.g. @2x). Is that clear?

**Comment by tenorviol** [comment]
Yes, that's clear. Thank you!

I think I'm going to break this pull request up. It's going to help if I get the infix tests working before pull requesting this rewrite.

**Pull request closed without merging**
