### PR TITLE
Fix for 26 failing tests

### PR DESCRIPTION
**Pull request by tenorviol**
This is a fix for the issue reported here: https://github.com/mutewinter/digest-brunch/issues/20

I updated all of the dependency versions and magically all the tests now pass. It's not clear that the false success positive is fixed, but I'm not sure how to test for that other than to keep an eye on it.

Other changes in this commit:
* Removed the `-R list` from `npm test` script because mocha 2 kind of does that by default.
* Moved the couple of lines in test_helper into the test file because of an aversion to monkey patching. 
   I can remove this if you disagree and want it to be that way.
* Bumped the patch version to 1.4.1

### CODE REVIEW

**Comment by tenorviol** [comment]
Travis says yes! https://travis-ci.org/mutewinter/digest-brunch/builds/49821884

**Comment by tenorviol** [comment]
I was able to verify that the false success problem is still in effect. I suspect it has something to do with the FakeFs. I'm considering redoing that to just use the real file system.

**Comment by mutewinter** [comment]
You're a saint @tenorviol! Thanks for doing this. Let me know if I should merge now or if you still want to try to fix the fake successes.

**Comment by tenorviol** [comment]
Lol. Not if you knew me.

Please merge this if you're comfortable with the changes. I spent the morning trying to refactor the tests, but have to move on. Not sure when I can get back to this. There are two more tests that I marked as skipped because when I fixed their assertions one of them is failing, and the negative is difficult to prove.

**Comment by mutewinter** [comment]
Published `1.4.1`, thanks again!

**Pull request merged**
